artifact_uri: file:///C:/Users/Gomi/OneDrive - Universidad Pontificia Comillas/5ºIMAT/Ingenieria
  de Modelos/practica 2/mlops-practica-icai/None/0/d865bb04f0894fefb2fa3eb4e88fe639/artifacts
end_time: 1761296778644
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: d865bb04f0894fefb2fa3eb4e88fe639
run_name: angry-goat-658
run_uuid: d865bb04f0894fefb2fa3eb4e88fe639
source_name: ''
source_type: 4
source_version: ''
start_time: 1761296750103
status: 3
tags: []
user_id: Gomi
