channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=25.2
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.0
  - configparser==6.0.0
  - numpy==1.26.4
  - packaging==23.2
  - pathlib==1.0.1
  - psutil==5.9.2
  - pyyaml==5.4.1
  - scikit-learn==1.3.0
  - scipy==1.13.0
  - typing-extensions==4.15.0
name: mlflow-env
