artifact_uri: file:///C:/Users/Gomi/OneDrive - Universidad Pontificia Comillas/5ºIMAT/Ingenieria
  de Modelos/practica 2/mlops-practica-icai/None/0/f5df348400cd4957b2c2b8d4c4ad5977/artifacts
end_time: 1761297085337
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: f5df348400cd4957b2c2b8d4c4ad5977
run_name: wistful-ram-887
run_uuid: f5df348400cd4957b2c2b8d4c4ad5977
source_name: ''
source_type: 4
source_version: ''
start_time: 1761297079834
status: 3
tags: []
user_id: Gomi
